### PR TITLE
Remove consistency checks from env

### PR DESCRIPTION
**Pull request by Zelldon**
closes https://github.com/zeebe-io/benchmark-helm/issues/23

The env variables have overwritten everytime the value if they are set in the zeebe.config configmap

### CODE REVIEW

**Review by oleschoenburg — COMMENTED** [review]
I think we should still enable them by default! Just through `zeebe.config`, not through the env variables.

**Comment by Zelldon** [comment]
@oleschoenburg I expected that they are enabled per default now, not? Shouldn't we fix that then in the zeebe repo?

**Comment by Zelldon** [comment]
Ok weird. I somehow have expected we enabled them, then I agree. I will move them.

**Review by oleschoenburg — APPROVED** [review]
Nice, thanks! :rocket:

**Comment by Zelldon** [comment]
@oleschoenburg looks like we have some rate limiting with the helm camunda platform helm chart 

I guess we have to fix this before we continue here.

**Comment by oleschoenburg** [comment]
Hm, is the test harness no caching downloaded helm charts? Maybe it helps to download the camunda-platform helm chart first?

**Pull request merged**
